package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 13 10:11:39 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HMOOptionMasterVORowImpl extends ViewRowImpl {


    public static final int ENTITY_HMOOPTIONMASTEREO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        HmoOptionsId,
        HmoOptions,
        HmoType,
        ResiAddress,
        ContactPersonName,
        EmailAddress,
        ContactNumber,
        Comments,
        ActiveFlag,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        Name_Trns,
        Number_Trns,
        Email_Trns,
        Group_Trns,
        Cadre_Trns,
        BusinessUnitId,
        PersonId,
        PlanName,
        HmoMasterHdrId,
        HMOCategoryMasterVO,
        HMOHospitalMasterVO,
        Employee_View_ROVO,
        HMOType_ROVO,
        HMOMaster_VO1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HMOOPTIONSID = AttributesEnum.HmoOptionsId.index();
    public static final int HMOOPTIONS = AttributesEnum.HmoOptions.index();
    public static final int HMOTYPE = AttributesEnum.HmoType.index();
    public static final int RESIADDRESS = AttributesEnum.ResiAddress.index();
    public static final int CONTACTPERSONNAME = AttributesEnum.ContactPersonName.index();
    public static final int EMAILADDRESS = AttributesEnum.EmailAddress.index();
    public static final int CONTACTNUMBER = AttributesEnum.ContactNumber.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int ACTIVEFLAG = AttributesEnum.ActiveFlag.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int NAME_TRNS = AttributesEnum.Name_Trns.index();
    public static final int NUMBER_TRNS = AttributesEnum.Number_Trns.index();
    public static final int EMAIL_TRNS = AttributesEnum.Email_Trns.index();
    public static final int GROUP_TRNS = AttributesEnum.Group_Trns.index();
    public static final int CADRE_TRNS = AttributesEnum.Cadre_Trns.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int PLANNAME = AttributesEnum.PlanName.index();
    public static final int HMOMASTERHDRID = AttributesEnum.HmoMasterHdrId.index();
    public static final int HMOCATEGORYMASTERVO = AttributesEnum.HMOCategoryMasterVO.index();
    public static final int HMOHOSPITALMASTERVO = AttributesEnum.HMOHospitalMasterVO.index();
    public static final int EMPLOYEE_VIEW_ROVO = AttributesEnum.Employee_View_ROVO.index();
    public static final int HMOTYPE_ROVO = AttributesEnum.HMOType_ROVO.index();
    public static final int HMOMASTER_VO1 = AttributesEnum.HMOMaster_VO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HMOOptionMasterVORowImpl() {
    }

    /**
     * Gets HMOOptionMasterEO entity object.
     * @return the HMOOptionMasterEO
     */
    public EntityImpl getHMOOptionMasterEO() {
        return (EntityImpl) getEntity(ENTITY_HMOOPTIONMASTEREO);
    }

    /**
     * Gets the attribute value for HMO_OPTIONS_ID using the alias name HmoOptionsId.
     * @return the HMO_OPTIONS_ID
     */
    public BigDecimal getHmoOptionsId() {
        return (BigDecimal) getAttributeInternal(HMOOPTIONSID);
    }

    /**
     * Sets <code>value</code> as attribute value for HMO_OPTIONS_ID using the alias name HmoOptionsId.
     * @param value value to set the HMO_OPTIONS_ID
     */
    public void setHmoOptionsId(BigDecimal value) {
        setAttributeInternal(HMOOPTIONSID, value);
    }

    /**
     * Gets the attribute value for HMO_OPTIONS using the alias name HmoOptions.
     * @return the HMO_OPTIONS
     */
    public String getHmoOptions() {
        return (String) getAttributeInternal(HMOOPTIONS);
    }

    /**
     * Sets <code>value</code> as attribute value for HMO_OPTIONS using the alias name HmoOptions.
     * @param value value to set the HMO_OPTIONS
     */
    public void setHmoOptions(String value) {
        setAttributeInternal(HMOOPTIONS, value);
    }

    /**
     * Gets the attribute value for HMO_TYPE using the alias name HmoType.
     * @return the HMO_TYPE
     */
    public String getHmoType() {
        return (String) getAttributeInternal(HMOTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for HMO_TYPE using the alias name HmoType.
     * @param value value to set the HMO_TYPE
     */
    public void setHmoType(String value) {
        setAttributeInternal(HMOTYPE, value);
    }

    /**
     * Gets the attribute value for RESI_ADDRESS using the alias name ResiAddress.
     * @return the RESI_ADDRESS
     */
    public String getResiAddress() {
        return (String) getAttributeInternal(RESIADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for RESI_ADDRESS using the alias name ResiAddress.
     * @param value value to set the RESI_ADDRESS
     */
    public void setResiAddress(String value) {
        setAttributeInternal(RESIADDRESS, value);
    }

    /**
     * Gets the attribute value for CONTACT_PERSON_NAME using the alias name ContactPersonName.
     * @return the CONTACT_PERSON_NAME
     */
    public String getContactPersonName() {
        return (String) getAttributeInternal(CONTACTPERSONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_PERSON_NAME using the alias name ContactPersonName.
     * @param value value to set the CONTACT_PERSON_NAME
     */
    public void setContactPersonName(String value) {
        setAttributeInternal(CONTACTPERSONNAME, value);
    }

    /**
     * Gets the attribute value for EMAIL_ADDRESS using the alias name EmailAddress.
     * @return the EMAIL_ADDRESS
     */
    public String getEmailAddress() {
        return (String) getAttributeInternal(EMAILADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL_ADDRESS using the alias name EmailAddress.
     * @param value value to set the EMAIL_ADDRESS
     */
    public void setEmailAddress(String value) {
        setAttributeInternal(EMAILADDRESS, value);
    }

    /**
     * Gets the attribute value for CONTACT_NUMBER using the alias name ContactNumber.
     * @return the CONTACT_NUMBER
     */
    public String getContactNumber() {
        return (String) getAttributeInternal(CONTACTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_NUMBER using the alias name ContactNumber.
     * @param value value to set the CONTACT_NUMBER
     */
    public void setContactNumber(String value) {
        setAttributeInternal(CONTACTNUMBER, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for ACTIVE_FLAG using the alias name ActiveFlag.
     * @return the ACTIVE_FLAG
     */
    public String getActiveFlag() {
        return (String) getAttributeInternal(ACTIVEFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE_FLAG using the alias name ActiveFlag.
     * @param value value to set the ACTIVE_FLAG
     */
    public void setActiveFlag(String value) {
        setAttributeInternal(ACTIVEFLAG, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Name_Trns.
     * @return the Name_Trns
     */
    public String getName_Trns() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("FullName").toString();
            }
            return name;
        } else {
        return (String) getAttributeInternal(NAME_TRNS);}
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Name_Trns.
     * @param value value to set the  Name_Trns
     */
    public void setName_Trns(String value) {
        setAttributeInternal(NAME_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Number_Trns.
     * @return the Number_Trns
     */
    public String getNumber_Trns() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            System.out.println("Person Id ------ " + type);
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("PersonNumber").toString();
                System.out.println("Emp name ---- " + name);
            }
            return name;
        } else {
            return (String) getAttributeInternal(NUMBER_TRNS);

        }
        //  return (String) getAttributeInternal(NUMBER_TRNS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Number_Trns.
     * @param value value to set the  Number_Trns
     */
    public void setNumber_Trns(String value) {
        setAttributeInternal(NUMBER_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Email_Trns.
     * @return the Email_Trns
     */
    public String getEmail_Trns() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("EmailAddress").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(EMAIL_TRNS);
        }


        // return (String) getAttributeInternal(EMAIL_TRNS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Email_Trns.
     * @param value value to set the  Email_Trns
     */
    public void setEmail_Trns(String value) {
        setAttributeInternal(EMAIL_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Group_Trns.
     * @return the Group_Trns
     */
    public String getGroup_Trns() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("BusinessUnitName").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(GROUP_TRNS);
        }


        // return (String) getAttributeInternal(GROUP_TRNS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Group_Trns.
     * @param value value to set the  Group_Trns
     */
    public void setGroup_Trns(String value) {
        setAttributeInternal(GROUP_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Cadre_Trns.
     * @return the Cadre_Trns
     */
    public String getCadre_Trns() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("Cadre").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(CADRE_TRNS);
        }
       // return (String) getAttributeInternal(CADRE_TRNS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Cadre_Trns.
     * @param value value to set the  Cadre_Trns
     */
    public void setCadre_Trns(String value) {
        setAttributeInternal(CADRE_TRNS, value);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @return the BUSINESS_UNIT_ID
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @param value value to set the BUSINESS_UNIT_ID
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for PERSON_ID using the alias name PersonId.
     * @return the PERSON_ID
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId.
     * @param value value to set the PERSON_ID
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for PLAN_NAME using the alias name PlanName.
     * @return the PLAN_NAME
     */
    public String getPlanName() {
        return (String) getAttributeInternal(PLANNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PLAN_NAME using the alias name PlanName.
     * @param value value to set the PLAN_NAME
     */
    public void setPlanName(String value) {
        setAttributeInternal(PLANNAME, value);
    }

    /**
     * Gets the attribute value for HMO_MASTER_HDR_ID using the alias name HmoMasterHdrId.
     * @return the HMO_MASTER_HDR_ID
     */
    public BigDecimal getHmoMasterHdrId() {
        return (BigDecimal) getAttributeInternal(HMOMASTERHDRID);
    }

    /**
     * Sets <code>value</code> as attribute value for HMO_MASTER_HDR_ID using the alias name HmoMasterHdrId.
     * @param value value to set the HMO_MASTER_HDR_ID
     */
    public void setHmoMasterHdrId(BigDecimal value) {
        setAttributeInternal(HMOMASTERHDRID, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HMOCategoryMasterVO.
     */
    public RowIterator getHMOCategoryMasterVO() {
        return (RowIterator) getAttributeInternal(HMOCATEGORYMASTERVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HMOHospitalMasterVO.
     */
    public RowIterator getHMOHospitalMasterVO() {
        return (RowIterator) getAttributeInternal(HMOHOSPITALMASTERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Employee_View_ROVO.
     */
    public RowSet getEmployee_View_ROVO() {
        return (RowSet) getAttributeInternal(EMPLOYEE_VIEW_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> HMOType_ROVO.
     */
    public RowSet getHMOType_ROVO() {
        return (RowSet) getAttributeInternal(HMOTYPE_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> HMOMaster_VO1.
     */
    public RowSet getHMOMaster_VO1() {
        return (RowSet) getAttributeInternal(HMOMASTER_VO1);
    }
}

