package model.svo;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 02 16:54:10 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LookupValues_SVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        s_no,
        lookup_value_code,
        lookup_value_name,
        parent_code;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int S_NO = AttributesEnum.s_no.index();
    public static final int LOOKUP_VALUE_CODE = AttributesEnum.lookup_value_code.index();
    public static final int LOOKUP_VALUE_NAME = AttributesEnum.lookup_value_name.index();
    public static final int PARENT_CODE = AttributesEnum.parent_code.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LookupValues_SVORowImpl() {
    }
}

