package model.svo;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 02 16:51:46 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LookupType_SVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        s_no,
        lookup_type_code,
        lookup_type_value,
        hmo_type;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int S_NO = AttributesEnum.s_no.index();
    public static final int LOOKUP_TYPE_CODE = AttributesEnum.lookup_type_code.index();
    public static final int LOOKUP_TYPE_VALUE = AttributesEnum.lookup_type_value.index();
    public static final int HMO_TYPE = AttributesEnum.hmo_type.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LookupType_SVORowImpl() {
    }
}

