package model.svo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 02 16:54:11 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LookupValues_SVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LookupValues_SVOImpl() {
    }
}

