package model.am;


import java.math.BigDecimal;


import java.sql.CallableStatement;
import java.sql.SQLException;

import java.sql.Types;


import model.am.common.Oando_AM;

import model.vo.DutyAllowance_VOImpl;


import model.vo.HMOBupaDtl_VOImpl;
import model.vo.HMOOptionMasterVOImpl;
import model.vo.HMOTradDtlImpl;

import oracle.adf.share.ADFContext;

import oracle.jbo.ApplicationModule;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 22 17:52:17 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Oando_AMImpl extends ApplicationModuleImpl implements ApplicationModule, Oando_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public Oando_AMImpl() {
    }


    /**
     * Container's getter for Lookup_View_ROVO.
     * @return Lookup_View_ROVO
     */
    public String createUop(BigDecimal hdrId) {
      //  String p_errorMessgae = null;
                String p_errorCode =null;
        try {
            String stmt1 = "begin xxfa_uop_depr_pkg.create_line(:p_uop_depr_hdr_id,:p_return_code,:p_return_msg); end;";
            CallableStatement cst = null;
            cst = this.getDBTransaction().createCallableStatement(stmt1, 0);
            cst.setObject("p_uop_depr_hdr_id", hdrId);
            cst.registerOutParameter("p_return_code", Types.VARCHAR);
            cst.registerOutParameter("p_return_msg", Types.VARCHAR);
            cst.executeUpdate();
            if (cst.getObject("p_return_code")  != null) {
               // p_errorMessgae = cst.getObject("p_return_msg").toString();
                                p_errorCode = cst.getObject("p_return_code").toString();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return p_errorCode;
              
    }

    
    
//    
//    public String createUop(BigDecimal uop_depr_hdr_id) throws CommonJBOException,
//    SQLException{
//
//            java.math.BigDecimal p_uop_depr_hdr_id = new java.math.BigDecimal();
//
//            try {
//                p_uop_depr_hdr_id = new java.math.BigDecimal(uop_depr_hdr_id);
//            } catch (CommonJBOException e) {
//                throw new CommonJBOException(e.getMessage());
//            }
//            String stmt1 = "begin \n" + "xxfa_uop_depr_pkg(:p_uop_depr_hdr_id);\n" + "end;";
//            CallableStatement cst = null;
//            try {
//                cst = this.getDBTransaction().createCallableStatement(stmt1, 0);
//                cst.setObject("p_uop_depr_hdr_id", p_uop_depr_hdr_id);
//            cst.registerOutParameter("p_return_code", Types.VARCHAR);
//            cst.registerOutParameter("p_return_msg", Types.VARCHAR);
//            cst.executeUpdate();
//            return cst.getString("p_return_code"+" "+"p_return_msg");
//            } catch (CommonJBOException e) {
//
//
//            throw new CommonJBOException(e.getMessage());
//
//            }
//            finally {
//                        if (cst != null) {
//                            try {
//                                cst.close();
//
//                            } catch (CommonJBOException e) {
//                                // _log.severe("exception occured in invokereceiptstatus method"+e.getmessage());
//                                // throw new commonjboexception(e.getmessage());
//
//                                return e.toString();
//                            }
//                        }
//                    }
//        }
//


    /**
     * Container's getter for DutyAllowance_VO1.
     * @return DutyAllowance_VO1
     */
    public DutyAllowance_VOImpl getDutyAllowance_VO() {
        return (DutyAllowance_VOImpl) findViewObject("DutyAllowance_VO");
    }

    /**
     * Container's getter for DutyAllow_ROVO1.
     * @return DutyAllow_ROVO1
     */
    public ViewObjectImpl getDutyAllow_ROVO() {
        return (ViewObjectImpl) findViewObject("DutyAllow_ROVO");
    }
    public BigDecimal getPersonId(String userName) {

        BigDecimal personId = new BigDecimal(0);
        ViewObjectImpl vo = this.getUsers_ROVO();
        ViewCriteria vc = vo.createViewCriteria();
        ViewCriteriaRow vcRow = vc.createViewCriteriaRow();
        vcRow.setAttribute("Username", userName);
        vc.addRow(vcRow);
        vo.applyViewCriteria(vc);
        vo.executeQuery();
        if (vo.getEstimatedRowCount() > 0) {
            personId = (BigDecimal) vo.first().getAttribute("PersonId");
            System.err.println(personId + "--------------personId impl");
            ADFContext.getCurrent()
                      .getSessionScope()
                      .put("personId", personId);
        }

        return personId;
    }

    public void filterUser() {
        String userName= ADFContext.getCurrent()
                                    .getSessionScope()
                                    .get("userName")
                                    .toString();
        System.err.println(userName + "--------------User Name");
        ViewObjectImpl vo = getDutyAllowance_VO();
        vo.setNamedWhereClauseParam("b_username", userName);
        vo.executeQuery();
        System.err.println(vo.getEstimatedRowCount() + "-------Row Count");
    }

    /**
     * Container's getter for Users_ROVO1.
     * @return Users_ROVO1
     */
    public ViewObjectImpl getUsers_ROVO() {
        return (ViewObjectImpl) findViewObject("Users_ROVO");
    }

    /**
     * Container's getter for Employee_View_ROVO1.
     * @return Employee_View_ROVO1
     */
    public ViewObjectImpl getEmployee_View_ROVO() {
        return (ViewObjectImpl) findViewObject("Employee_View_ROVO");
    }


    /**
     * Container's getter for HMOMaster_VO1.
     * @return HMOMaster_VO1
     */
    public ViewObjectImpl getHMOMaster_VO() {
        return (ViewObjectImpl) findViewObject("HMOMaster_VO");
    }

    /**
     * Container's getter for HMOBupaDtl_VO1.
     * @return HMOBupaDtl_VO1
     */
    public HMOBupaDtl_VOImpl getHMOBupaDtl_VO() {
        return (HMOBupaDtl_VOImpl) findViewObject("HMOBupaDtl_VO");
    }

    /**
     * Container's getter for HMOMaster_VL1.
     * @return HMOMaster_VL1
     */
    public ViewLinkImpl getHMOMaster_VL() {
        return (ViewLinkImpl) findViewLink("HMOMaster_VL");
    }

    /**
     * Container's getter for HMOTradDtl2.
     * @return HMOTradDtl2
     */
    public HMOTradDtlImpl getHMOTradDtl() {
        return (HMOTradDtlImpl) findViewObject("HMOTradDtl");
    }

    /**
     * Container's getter for HMOTrad_VL2.
     * @return HMOTrad_VL2
     */
    public ViewLinkImpl getHMOTrad_VL() {
        return (ViewLinkImpl) findViewLink("HMOTrad_VL");
    }

    /**
     * Container's getter for HMOOptionMasterVO1.
     * @return HMOOptionMasterVO1
     */
    public ViewObjectImpl getHMOOptionMasterVO() {
        return (ViewObjectImpl) findViewObject("HMOOptionMasterVO");
    }

    /**
     * Container's getter for HMOCategoryMasterVO1.
     * @return HMOCategoryMasterVO1
     */
    public ViewObjectImpl getHMOCategoryMasterVO() {
        return (ViewObjectImpl) findViewObject("HMOCategoryMasterVO");
    }

    /**
     * Container's getter for HMOOptCategoryVL1.
     * @return HMOOptCategoryVL1
     */
    public ViewLinkImpl getHMOOptCategoryVL() {
        return (ViewLinkImpl) findViewLink("HMOOptCategoryVL");
    }

    /**
     * Container's getter for HMOHospitalMasterVO1.
     * @return HMOHospitalMasterVO1
     */
    public ViewObjectImpl getHMOHospitalMasterVO() {
        return (ViewObjectImpl) findViewObject("HMOHospitalMasterVO");
    }

    /**
     * Container's getter for HMOOptHospitalVL1.
     * @return HMOOptHospitalVL1
     */
    public ViewLinkImpl getHMOOptHospitalVL() {
        return (ViewLinkImpl) findViewLink("HMOOptHospitalVL");
    }

    /**
     * Container's getter for HMOType_ROVO1.
     * @return HMOType_ROVO1
     */
    public ViewObjectImpl getHMOType_ROVO() {
        return (ViewObjectImpl) findViewObject("HMOType_ROVO");
    }

    /**
     * Container's getter for HMO_Category_ROVO1.
     * @return HMO_Category_ROVO1
     */
    public ViewObjectImpl getHMO_Category_ROVO1() {
        return (ViewObjectImpl) findViewObject("HMO_Category_ROVO1");
    }

    /**
     * Container's getter for HMO_Options_ROVO1.
     * @return HMO_Options_ROVO1
     */
    public ViewObjectImpl getHMO_Options_ROVO1() {
        return (ViewObjectImpl) findViewObject("HMO_Options_ROVO1");
    }
}
