package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 05 15:57:58 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HMOBupaDtl_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HMOBupaDtl_VOImpl() {
    }
}

