package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.eo.HMOMaster_EOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 05 16:03:28 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HMOMaster_VORowImpl extends ViewRowImpl {


    public static final int ENTITY_HMOMASTER_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Active,
        BupaCurrencyCode,
        BupaEligibleCost,
        BusinessUnitId,
        CreatedBy,
        CreationDate,
        HmoMasterHdrId,
        HmoPlanName,
        HmoPlanYear,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        Trans_Year,
        AxaLbCurrencyCode,
        AxaLbEligibleCost,
        HMOBupaDtl_VO,
        HMOTradDtl,
        HMOTradDtl1,
        Lookup_ROVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int BUPACURRENCYCODE = AttributesEnum.BupaCurrencyCode.index();
    public static final int BUPAELIGIBLECOST = AttributesEnum.BupaEligibleCost.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int HMOMASTERHDRID = AttributesEnum.HmoMasterHdrId.index();
    public static final int HMOPLANNAME = AttributesEnum.HmoPlanName.index();
    public static final int HMOPLANYEAR = AttributesEnum.HmoPlanYear.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int TRANS_YEAR = AttributesEnum.Trans_Year.index();
    public static final int AXALBCURRENCYCODE = AttributesEnum.AxaLbCurrencyCode.index();
    public static final int AXALBELIGIBLECOST = AttributesEnum.AxaLbEligibleCost.index();
    public static final int HMOBUPADTL_VO = AttributesEnum.HMOBupaDtl_VO.index();
    public static final int HMOTRADDTL = AttributesEnum.HMOTradDtl.index();
    public static final int HMOTRADDTL1 = AttributesEnum.HMOTradDtl1.index();
    public static final int LOOKUP_ROVO = AttributesEnum.Lookup_ROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HMOMaster_VORowImpl() {
    }

    /**
     * Gets HMOMaster_EO entity object.
     * @return the HMOMaster_EO
     */
    public HMOMaster_EOImpl getHMOMaster_EO() {
        return (HMOMaster_EOImpl) getEntity(ENTITY_HMOMASTER_EO);
    }

    /**
     * Gets the attribute value for ACTIVE using the alias name Active.
     * @return the ACTIVE
     */
    public String getActive() {
        return (String) getAttributeInternal(ACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE using the alias name Active.
     * @param value value to set the ACTIVE
     */
    public void setActive(String value) {
        setAttributeInternal(ACTIVE, value);
    }

    /**
     * Gets the attribute value for BUPA_CURRENCY_CODE using the alias name BupaCurrencyCode.
     * @return the BUPA_CURRENCY_CODE
     */
    public String getBupaCurrencyCode() {
        return (String) getAttributeInternal(BUPACURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for BUPA_CURRENCY_CODE using the alias name BupaCurrencyCode.
     * @param value value to set the BUPA_CURRENCY_CODE
     */
    public void setBupaCurrencyCode(String value) {
        setAttributeInternal(BUPACURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for BUPA_ELIGIBLE_COST using the alias name BupaEligibleCost.
     * @return the BUPA_ELIGIBLE_COST
     */
    public BigDecimal getBupaEligibleCost() {
        return (BigDecimal) getAttributeInternal(BUPAELIGIBLECOST);
    }

    /**
     * Sets <code>value</code> as attribute value for BUPA_ELIGIBLE_COST using the alias name BupaEligibleCost.
     * @param value value to set the BUPA_ELIGIBLE_COST
     */
    public void setBupaEligibleCost(BigDecimal value) {
        setAttributeInternal(BUPAELIGIBLECOST, value);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @return the BUSINESS_UNIT_ID
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @param value value to set the BUSINESS_UNIT_ID
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for HMO_MASTER_HDR_ID using the alias name HmoMasterHdrId.
     * @return the HMO_MASTER_HDR_ID
     */
    public BigDecimal getHmoMasterHdrId() {
        return (BigDecimal) getAttributeInternal(HMOMASTERHDRID);
    }

    /**
     * Sets <code>value</code> as attribute value for HMO_MASTER_HDR_ID using the alias name HmoMasterHdrId.
     * @param value value to set the HMO_MASTER_HDR_ID
     */
    public void setHmoMasterHdrId(BigDecimal value) {
        setAttributeInternal(HMOMASTERHDRID, value);
    }

    /**
     * Gets the attribute value for HMO_PLAN_NAME using the alias name HmoPlanName.
     * @return the HMO_PLAN_NAME
     */
    public String getHmoPlanName() {
        return (String) getAttributeInternal(HMOPLANNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for HMO_PLAN_NAME using the alias name HmoPlanName.
     * @param value value to set the HMO_PLAN_NAME
     */
    public void setHmoPlanName(String value) {
        setAttributeInternal(HMOPLANNAME, value);
    }

    /**
     * Gets the attribute value for HMO_PLAN_YEAR using the alias name HmoPlanYear.
     * @return the HMO_PLAN_YEAR
     */
    public String getHmoPlanYear() {
        return (String) getAttributeInternal(HMOPLANYEAR);
    }

    /**
     * Sets <code>value</code> as attribute value for HMO_PLAN_YEAR using the alias name HmoPlanYear.
     * @param value value to set the HMO_PLAN_YEAR
     */
    public void setHmoPlanYear(String value) {
        setAttributeInternal(HMOPLANYEAR, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Year.
     * @return the Trans_Year
     */
    public String getTrans_Year() {
        return (String) getAttributeInternal(TRANS_YEAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Year.
     * @param value value to set the  Trans_Year
     */
    public void setTrans_Year(String value) {
        setAttributeInternal(TRANS_YEAR, value);
    }

    /**
     * Gets the attribute value for AXA_LB_CURRENCY_CODE using the alias name AxaLbCurrencyCode.
     * @return the AXA_LB_CURRENCY_CODE
     */
    public String getAxaLbCurrencyCode() {
        return (String) getAttributeInternal(AXALBCURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for AXA_LB_CURRENCY_CODE using the alias name AxaLbCurrencyCode.
     * @param value value to set the AXA_LB_CURRENCY_CODE
     */
    public void setAxaLbCurrencyCode(String value) {
        setAttributeInternal(AXALBCURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for AXA_LB_ELIGIBLE_COST using the alias name AxaLbEligibleCost.
     * @return the AXA_LB_ELIGIBLE_COST
     */
    public BigDecimal getAxaLbEligibleCost() {
        return (BigDecimal) getAttributeInternal(AXALBELIGIBLECOST);
    }

    /**
     * Sets <code>value</code> as attribute value for AXA_LB_ELIGIBLE_COST using the alias name AxaLbEligibleCost.
     * @param value value to set the AXA_LB_ELIGIBLE_COST
     */
    public void setAxaLbEligibleCost(BigDecimal value) {
        setAttributeInternal(AXALBELIGIBLECOST, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HMOBupaDtl_VO.
     */
    public RowIterator getHMOBupaDtl_VO() {
        return (RowIterator) getAttributeInternal(HMOBUPADTL_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HMOTradDtl.
     */
    public RowIterator getHMOTradDtl() {
        return (RowIterator) getAttributeInternal(HMOTRADDTL);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HMOTradDtl1.
     */
    public RowIterator getHMOTradDtl1() {
        return (RowIterator) getAttributeInternal(HMOTRADDTL1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Lookup_ROVO.
     */
    public RowSet getLookup_ROVO() {
        return (RowSet) getAttributeInternal(LOOKUP_ROVO);
    }

}

