package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 26 14:23:27 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HMOTradDtlImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HMOTradDtlImpl() {
    }
}

