package model.vo;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 13 10:11:40 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HMOOptionMasterVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HMOOptionMasterVOImpl() {
    }

    /**
     * Returns the variable value for bv_ID.
     * @return variable value for bv_ID
     */
    public BigDecimal getbv_ID() {
        return (BigDecimal) ensureVariableManager().getVariableValue("bv_ID");
    }

    /**
     * Sets <code>value</code> for variable bv_ID.
     * @param value value to bind as bv_ID
     */
    public void setbv_ID(BigDecimal value) {
        ensureVariableManager().setVariableValue("bv_ID", value);
    }
}

